
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Provider_Name')
	ALTER TABLE [SSD].[Provider] ADD CONSTRAINT [UX_Provider_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Program_Name')
	ALTER TABLE [SSD].[Program] ADD CONSTRAINT [UX_Program_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='UX_User_EmailAddress')
	CREATE UNIQUE INDEX [UX_User_EmailAddress] ON [SSD].[User] (EmailAddress) WHERE EmailAddress <> 'Anonymous@sample.com'
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_User_UserKey')
	ALTER TABLE [SSD].[User] ADD CONSTRAINT [UX_User_UserKey] UNIQUE ([UserKey])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Category_Name')
	ALTER TABLE [SSD].[Category] ADD CONSTRAINT [UX_Category_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Priority_Name')
	ALTER TABLE [SSD].[Priority] ADD CONSTRAINT [UX_Priority_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Role_Name')
	ALTER TABLE [SSD].[Role] ADD CONSTRAINT [UX_Role_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_ServiceType_Name')
	ALTER TABLE [SSD].[ServiceType] ADD CONSTRAINT [UX_ServiceType_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Subject_Name')
	ALTER TABLE [SSD].[Subject] ADD CONSTRAINT [UX_Subject_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Property_EntityName_Name')
	ALTER TABLE [SSD].[Property] ADD CONSTRAINT [UX_Property_EntityName_Name] UNIQUE ([EntityName], [Name])
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_ServiceOffering_ProviderId_ServiceTypeId')
	ALTER TABLE [SSD].[ServiceOffering] DROP CONSTRAINT [UX_ServiceOffering_ProviderId_ServiceTypeId]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_ServiceOffering_ProviderId_ServiceTypeId_ProgramId')
	ALTER TABLE [SSD].[ServiceOffering] ADD CONSTRAINT [UX_ServiceOffering_ProviderId_ServiceTypeId_ProgramId] UNIQUE ([ProviderId], [ServiceTypeId], [ProgramId])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_UserRoles_UserId_RoleId')
	ALTER TABLE [SSD].[UserRoles] ADD CONSTRAINT [UX_UserRoles_UserId_RoleId] UNIQUE ([UserId], [RoleId])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_CustomField_Name')
	ALTER TABLE [SSD].[CustomField] ADD CONSTRAINT [UX_CustomField_Name] UNIQUE ([Name])
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_FulfillmentStatus_Name')
	ALTER TABLE [SSD].[FulfillmentStatus] ADD CONSTRAINT [UX_FulfillmentStatus_Name] UNIQUE ([Name])
GO
