
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='UX_Subject_Name')
	ALTER TABLE [SSD].[Subject] DROP CONSTRAINT [UX_Subject_Name]
GO

UPDATE [SSD].[Subject] SET [Name] = LEFT([Name], 20)
GO
